version: "3.3"

services:
  api:
    container_name: "svc"
    build: ./svc
    ports:
      - "8080:8080"
    volumes:
      - ./../backend:/app
    networks:
      - local-net

networks:
  local-net:
    driver: bridge